name: 'Setup Linode CLI'
description: 'Install and configure Linode CLI with authentication'
inputs:
  linode_token:
    description: 'Linode API token'
    required: true
outputs:
  cli_version:
    description: 'Installed CLI version'
    value: ${{ steps.install.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Install Linode CLI
      id: install
      shell: bash
      run: |
        pip install linode-cli
        VERSION=$(linode-cli --version | head -1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "✅ Linode CLI installed: $VERSION"
      env:
        LINODE_CLI_TOKEN: ${{ inputs.linode_token }}
    
    - name: Configure CLI with token
      shell: bash
      run: |
        # Configure CLI non-interactively
        mkdir -p ~/.config
        cat > ~/.config/linode-cli << EOF
        [DEFAULT]
        default-user = default-cli
        
        [default-cli]
        token = ${{ inputs.linode_token }}
        region = us-east
        type = g6-nanode-1
        image = linode/ubuntu20.04
        EOF
        echo "✅ Linode CLI configured with token"
    
    - name: Verify CLI authentication
      shell: bash
      run: |
        linode-cli linodes list --text --no-headers > /dev/null || exit 1
        echo "✅ Linode CLI authentication verified"
      env:
        LINODE_CLI_TOKEN: ${{ inputs.linode_token }}