title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /initramfs-linux.img
options rd.luks.name=24ca3551-a768-48fb-ba45-5a26486825fe=cryptlvm root=/dev/vg0/lv_root rw resume=UUID=95003667-ee15-4508-a7b4-d5d483988907 mem_sleep_default=deep
