title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /initramfs-linux.img
options rd.luks.name=c44fd19f-7448-40bf-896f-0125756bd6bf=cryptlvm root=/dev/vg0/lv_root rw nvidia_drm.modeset=1
